### ISSUE TITLE
Hi. Please remove my fonts from your Git. 

### ISSUE THREAD

**Issue by okay-type** [UWEcoCAR/UWCenterStack#48]
Hello, 

I tried to find a direct contact to reach out to but there weren't any listed. 

Your UWCenterStack repo contains my font software, Alright Sans. 
These fonts are not open source and you are not allowed to publicly share them. 
Please remove the files immediately. 
https://github.com/UWEcoCAR/UWCenterStack/tree/master/fonts/alrightsans

Thanks, 
Jackson Cavanaugh
Okay Type

**Comment by stein3** [comment]
Just removed from the repo. Sorry about that!
